require 'yaml'
require 'fileutils'

confDir = File.expand_path(File.dirname(__FILE__))
config = {
  local: confDir + '/config/main.yml'
}

options = YAML.load_file config[:local]

Vagrant.configure(options['vagrant_api_version']) do |config|
  config.vm.box = options['box']
  config.vm.hostname = options['hostname']
  config.vm.define options['machine_name']
  config.vm.box_check_update = options['box_check_update']
  config.vm.network "forwarded_port", guest: 3306, host: 3309
  config.vm.network options['network'], ip: options['ip']  
  # config.vm.provision :hostmanager
  # config.hostmanager.enabled            = true
  # config.hostmanager.manage_host        = true
  # config.hostmanager.ignore_private_ip  = false
  # config.hostmanager.include_offline    = true

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = options['memory']
    vb.cpus = options['cpus']
    vb.name = options['machine_name']
  end

  config.vm.synced_folder options['synced_folder'], options['vm_synced_folder'], type: "virtualbox", owner: options['owner'], group: options['group'], mount_options: [options['mount_options']]
  config.vm.provision 'shell', path: './scripts/bootstrap.sh'
end
