AppBundle\Entity\Comment:
    type: entity
    table: comments
    indexes:
        fk_comments_id_posts_id_idx:
            columns:
                - post_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        postId:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: post_id
        parentId:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: parent_id
        description:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
        active:
            type: integer
            nullable: false
            options:
                default: 1
        createdAt:
            type: datetime
            nullable: false
            options:
                default: CURRENT_TIMESTAMP
            column: created_at
        updatedAt:
            type: datetime
            nullable: true
            column: updated_at
        deletedAt:
            type: datetime
            nullable: true
            column: deleted_at
    manyToOne:
        post:
            targetEntity: Post
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: comments
            joinColumns:
                post_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
