AppBundle\Entity\Post:
    type: entity
    table: posts
    repositoryClass: AppBundle\Repository\PostRepository
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        categoryId:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: category_id
        title:
            type: string
            nullable: false
            length: 150
            options:
                fixed: false
        summary:
            type: string
            nullable: true
            length: 300
            options:
                fixed: false
        content:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
        active:
            type: integer
            nullable: false
            options:
                default: 1
        createdAt:
            type: datetime
            nullable: false
            options:
                default: CURRENT_TIMESTAMP
            column: created_at
        updatedAt:
            type: datetime
            nullable: true
            column: updated_at
        deletedAt:
            type: datetime
            nullable: true
            column: deleted_at
    oneToMany:
        comments:
            targetEntity: Comment
            fetch: LAZY
            mappedBy: post
            inversedBy: null
            orphanRemoval: false

    manyToOne:
        category:
            targetEntity: Category
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: posts
            joinColumn:
                name: category_id
                referencedColumnName: id
#                nullable: true
            orphanRemoval: false
    lifecycleCallbacks: {  }
